In [6]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [7]:
inputs = [0, 1, 2, 3]
labels = [1, 0 , 1, 0]

In [8]:
dataset = tf.data.Dataset.from_tensor_slices((inputs, labels))

In [9]:
for item in dataset:
    print(item)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


In [10]:
inputs = np.asarray(inputs)
labels = np.asarray(labels)
inputs

array([0, 1, 2, 3])

In [11]:
dataset = tf.data.Dataset.from_tensor_slices((inputs, labels))
for item in dataset:
    print(item)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=int64, numpy=2>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=int64, numpy=3>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)


In [14]:
df = pd.DataFrame({
    'inputs' : [0, 1,2,3],
    'labels' : [1, 0, 1,0]

})

In [15]:
df

inputs  labels
0       0       1
1       1       0
2       2       1
3       3       0

In [16]:
df['inputs'].values

array([0, 1, 2, 3])

In [17]:
dataset = tf.data.Dataset.from_tensor_slices((df['inputs'].values, df['labels'].values))
for item in dataset:
    print(item)
# only difference is, it is generating dtype=int64

(<tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=int64, numpy=2>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=int64, numpy=3>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)


 ---

# Read data from file

In [42]:
dataset = tf.data.experimental.make_csv_dataset(
    "MSFTData.csv", 
    batch_size= 16,
    field_delim=',',
    select_columns = ['Date','Price', 'Open', 'High', 'Low', 'Vol.', 'Change %'],
    label_name= 'Date'
    
)

ValueError: Column Date specified in `select_columns` must be of one of the columns: dict_keys(['\ufeff"Date"', 'Price', 'Open', 'High', 'Low', 'Vol.', 'Change %']).

In [43]:
for item in dataset.take(3):
    print(item)

(<tf.Tensor: shape=(16, 2), dtype=float64, numpy=
array([[284.91, 269.6 ],
       [239.82, 233.87],
       [281.92, 281.62],
       [271.87, 246.44],
       [249.68, 238.07],
       [255.14, 213.43],
       [247.81, 219.35],
       [261.47, 260.66],
       [308.31, 270.  ],
       [249.42, 245.47],
       [256.83, 241.51],
       [298.79, 271.52],
       [280.74, 245.94],
       [232.9 , 232.73],
       [270.9 , 243.  ],
       [310.98, 276.05]])>, <tf.Tensor: shape=(16,), dtype=string, numpy=
array([b'07/01/2021', b'12/01/2022', b'09/01/2021', b'05/01/2022',
       b'05/01/2021', b'11/01/2022', b'01/01/2023', b'08/01/2022',
       b'03/01/2022', b'02/01/2023', b'06/01/2022', b'02/01/2022',
       b'07/01/2022', b'09/01/2022', b'06/01/2021', b'01/01/2022'],
      dtype=object)>)


In [30]:
data = pd.read_csv("MSFTData.csv")
data.head()

Date   Price    Open    High     Low     Vol. Change %
0  04/01/2021  252.18  238.47  263.19  238.05  568.70M    6.96%
1  05/01/2021  249.68  253.40  254.35  238.07  495.09M   -0.99%
2  06/01/2021  270.90  251.23  271.65  243.00  508.57M    8.50%
3  07/01/2021  284.91  269.61  290.15  269.60  522.69M    5.17%
4  08/01/2021  301.88  286.36  305.84  283.74  441.33M    5.96%

In [32]:
dataset = tf.data.Dataset.from_tensor_slices((data[['Price','Low']].values, data['Date'].values))

In [33]:
for item in dataset.take(1):
    print(item)

(<tf.Tensor: shape=(2,), dtype=float64, numpy=array([252.18, 238.05])>, <tf.Tensor: shape=(), dtype=string, numpy=b'04/01/2021'>)


In [34]:
dataset = dataset.shuffle(10000).batch(16,drop_remainder = True )

In [44]:
for item in dataset:
    print(item)

(<tf.Tensor: shape=(16, 2), dtype=float64, numpy=
array([[239.82, 233.87],
       [277.52, 270.  ],
       [247.81, 219.35],
       [252.18, 238.05],
       [256.83, 241.51],
       [284.91, 269.6 ],
       [330.59, 326.37],
       [336.32, 317.25],
       [270.9 , 243.  ],
       [281.92, 281.62],
       [310.98, 276.05],
       [331.62, 280.25],
       [277.66, 245.63],
       [280.74, 245.94],
       [298.79, 271.52],
       [249.68, 238.07]])>, <tf.Tensor: shape=(16,), dtype=string, numpy=
array([b'12/01/2022', b'04/01/2022', b'01/01/2023', b'04/01/2021',
       b'06/01/2022', b'07/01/2021', b'11/01/2021', b'12/01/2021',
       b'06/01/2021', b'09/01/2021', b'01/01/2022', b'10/01/2021',
       b'03/01/2023', b'07/01/2022', b'02/01/2022', b'05/01/2021'],
      dtype=object)>)
