In [3]:
import pandas as pd


In [5]:
data = pd.read_csv('tesla_tweets.csv', sep='|')
data.head()

created_at   edit_history_tweet_ids  \
0  2023-04-09T21:53:12.000Z  ['1645183104896876545']   
1  2023-04-09T21:53:12.000Z  ['1645183104343048197']   
2  2023-04-09T21:53:12.000Z  ['1645183103550496771']   
3  2023-04-09T21:53:12.000Z  ['1645183103332384769']   
4  2023-04-09T21:53:12.000Z  ['1645183102195494913']   

                                                text                   id  \
0  RT @nytimes: Elon Musk's many tweaks to Twitte...  1645183104896876545   
1  RT @elonmusk: Tesla opening Megapack factory i...  1645183104343048197   
2  RT @OmarRiverosays: BREAKING NEWS: Yahoo News ...  1645183103550496771   
3  RT @blockkbusiness: Is it true Tesla is buildi...  1645183103332384769   
4  RT @blockkbusiness: Is it true Tesla is buildi...  1645183102195494913   

  lang withheld  
0   en      NaN  
1   en      NaN  
2   en      NaN  
3   en      NaN  
4   en      NaN

In [8]:
from transformers import BertTokenizer, BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained("bert-base-uncased") #uncased

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [9]:
sample = "We are going to implement sentiment analysis with BERT!"

In [11]:
tokens = tokenizer.tokenize(sample)
print(tokens)

['we', 'are', 'going', 'to', 'implement', 'sentiment', 'analysis', 'with', 'bert', '!']


In [12]:
token_ids = tokenizer.convert_tokens_to_ids(tokens)
print(token_ids)

[2057, 2024, 2183, 2000, 10408, 15792, 4106, 2007, 14324, 999]


In [13]:
tokenizer.pad_token, tokenizer.pad_token_id

('[PAD]', 0)

In [14]:
tokenizer.unk_token, tokenizer.unk_token_id

('[UNK]', 100)

In [16]:
tokenizer.cls_token, tokenizer.cls_token_id

('[CLS]', 101)

In [17]:
tokenizer.sep_token, tokenizer.sep_token_id

('[SEP]', 102)

In [19]:
manual_sample = '[CLS]' + sample + '[SEP]'
tokens = tokenizer.tokenize(manual_sample)
token_ids = tokenizer.convert_tokens_to_ids(tokens)

print(manual_sample)
print(tokens)
print(token_ids)

[CLS]We are going to implement sentiment analysis with BERT![SEP]
['[CLS]', 'we', 'are', 'going', 'to', 'implement', 'sentiment', 'analysis', 'with', 'bert', '!', '[SEP]']
[101, 2057, 2024, 2183, 2000, 10408, 15792, 4106, 2007, 14324, 999, 102]


In [24]:
encoding = tokenizer.encode_plus(sample, max_length=24, truncation=True, pad_to_max_length=True,
                                add_special_tokens=True, return_attention_mask=True,
                                return_tensors='tf')


In [25]:
encoding

{'input_ids': <tf.Tensor: shape=(1, 24), dtype=int32, numpy=
array([[  101,  2057,  2024,  2183,  2000, 10408, 15792,  4106,  2007,
        14324,   999,   102,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 24), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 24), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0]], dtype=int32)>}

In [26]:
encoding['input_ids']

<tf.Tensor: shape=(1, 24), dtype=int32, numpy=
array([[  101,  2057,  2024,  2183,  2000, 10408, 15792,  4106,  2007,
        14324,   999,   102,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0]], dtype=int32)>

In [28]:
encoding['attention_mask']

<tf.Tensor: shape=(1, 24), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0]], dtype=int32)>